Fix error in Installation commands
amantiwari1/youtube-GUI pull request #2
Opened 2021-03-12 19:31 UTC by raulpy271

The command `python -m venv pip` will create a directory called `pip` and create an environment inside it. The correct command is `python -m venv .`, where the dot is the current path.

Another mistake is `python install -r requirement.txt` because python will search for a file called `install`, use pip to fix it.

edit: In Linux to represent the current path is used a dot. but I don't know if in windows the behavior is the same.

2021-03-12 19:55 UTC, amantiwari1 commented
It will directory called `pip` which allow us to ignore  using `.gitignore` and it  won't upload all env files to github repo and i don't know how to ignore file using current path. so we could easy ignore directory  so Change it to 'python -m venv pip'  or add `/etc` , `/Include`,  `/Lib` , `/Scripts`, `pyvenv.cfg`  and `share` to .gitignore file.

2021-03-12 22:57 UTC, raulpy271 commented
I thought it would be an error because I don't have seen a project using the `env`s files in a separated directory, it's most common to put them in the top-level directory and add all files in .gitignore like the [`.gitignore`](https://github.com/github/gitignore/blob/master/Python.gitignore) suggested by github. But, After your explanation I agree, it's more simple to use only the `env` path in the `.gitignore`. Thanks for the idea.

2021-03-12 23:00 UTC, raulpy271 commented
About the usage of the `python` instead of `pip`, do you agree that it's an error?

2021-03-13 06:04 UTC, amantiwari1 commented
@raulpy271  I agree!

2021-03-13 06:08 UTC, amantiwari1 requested changes

2021-03-13 06:08 UTC, amantiwari1 commented on README.md
> +python -m venv .
please change . to `env` or `pip` then I will merge it to main branch

2021-03-13 10:53 UTC, raulpy271 commented
Nice, I changed the path to store `env` files

2021-03-13 12:11 UTC, merged